= TEIID Translator Arche Type

This maven project is use to create the TEIID Translator archetype, which then can be used to generate a new translator project.

Teiid 12.0+ should use archetypeVersion 12.0.0+ with archetypeGroupId org.teiid.arche-types. Teiid 10/11 should use archetypeVersion 10.0.0+ with archetypeGroupId org.teiid.arche-types.  Teiid 8.x and 9.x should use archetypeVersion 9.0.1+ and archetypeGroupId org.jboss.teiid.arche-type

== Generate Project

After the arche type is installed, then to generate a translator project, do the following:

-  'cd' into the teiid/connectors directory (assuming you have checked out teiid from github) or to the
	location you want the connector project created
-  use the following template to generate the project:

***********
* TEMPLATE
***********

[source,java]
----
mvn archetype:generate               \
  -DarchetypeGroupId=org.teiid.arche-types               \
  -DarchetypeArtifactId=translator-archetype          \
  -DarchetypeVersion=${archetypeVersion}               \
  -DgroupId=${groupId}   				\
  -DartifactId=translator-${translator-type}	\
  -Dpackage=${package}    \
  -Dversion=${version}    \
  -Dtranslator-type=${translator-type}   \
  -Dtranslator-name=${translator-name}
  -Dteiid-version=${teiid-version}
----  

********
* where:
********

[source,java]
----
  -DarchetypeGroupId    -  is the group ID for the arche type to use to generate
  -DarchetypeArtifactId -  is the artifact ID for the arche type to use to generate
  -DarchetypeVersion	-  is the version for the arche type to use to generate
  -DgroupId		-  (user defined) group ID for the new translator project pom.xml
  -DartifactId		-  (user defined) artifact ID for the new translator project pom.xml
  -Dpackage		-  (user defined) the package structure where the java and resource files will be created
  -Dversion		-  (user defined) the version that the new connector project pom.xml will be
  -Dtranslator-type	-  (user defined) the translator type that's used by Teiid when mapping the physical source to the translator to use 
  -Dtranslator-name	-  (user defined) the translator name thats used for name the java class names
  -Dteiid-version   -  [optional] the Teiid version the connector will depend upon, if not specified will default 
----

*********
* EXAMPLE
*********

-  this is an example of the template that can be run:

[source,java]
----
mvn archetype:generate                    \
  -DarchetypeGroupId=org.teiid.arche-types   \
  -DarchetypeArtifactId=translator-archetype  \
  -DarchetypeVersion=10.0.0  \
  -DgroupId=org.example  \
  -DartifactId=translator-type  \
  -Dpackage=org.example.translator.type    \
  -Dversion=0.0.1-SNAPSHOT	\
  -Dtranslator-type=type  \
  -Dtranslator-name=Type  \
  -Dteiid-version=10.2.0
----

When executed, you will be asked to confirm the properties

Confirm properties configuration:
groupId: org.example
artifactId: translator-type
version: 0.0.1-SNAPSHOT
package: org.example.translator.type
teiid-version: 10.2.0
translator-name: Type
translator-type: type
 Y: : y


type Y (yes) and press enter, and the creation of the translator project will be done

